exclude: ^dist/
repos:
- repo: local
  hooks:
  - id: npm-build
    name: run npm build
    entry: npm run build
    language: system
    files: \.(ts)$
    pass_filenames: false

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.15.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-merge-conflict

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v4.0.0-alpha.8
  hooks:
  - id: prettier
    files: \.(ts|json|md)$
