name: Upload to Nexus Mods
description: Uploads a file to Nexus Mods
branding:
  icon: upload-cloud
  color: orange
inputs:
  api_key:
    description: API key
    required: true
  mod_id:
    description: Mod ID on Nexus Mods
    required: true
  game_domainname:
    description: Game Domain Name on Nexus Mods
    required: true
  filename:
    description: Name of the zip file to upload
    required: true
  version:
    description: Version string for the uploaded file (e.g., 1.0.0)
    required: true
  fileCategory:
    description: 'File category for the uploaded file (default: 1)'
    required: false
    default: '1'
runs:
  using: node20
  main: dist/index.js
