name: Upload to Nexumods
description: Zips the repository and uploads it to Nexumods
branding:
  icon: upload-cloud
  color: orange
inputs:
  api_key:
    description: API key
    required: true
  mod_id:
    description: Mod ID on Nexumods
    required: true
  game_id:
    description: Game ID on Nexumods
    required: true
  filename:
    description: Name of the zip file to upload
    required: true
  file_id:
    description: File ID to update
    required: true
  version:
    description: Version string for the uploaded file (e.g., 1.0.0)
    required: true
  fileCategory:
    description: 'File category for the uploaded file (default: 1)'
    required: false
    default: '1'
  removeOldVersion:
    description: 'Remove old version of the file (default: true)'
    required: false
    default: 'true'
  latestModVersion:
    description: 'Mark as latest mod version (default: true)'
    required: false
    default: 'true'
runs:
  using: node20
  main: dist/index.js
