/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/uploads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get upload
         * @description Get the state of an upload session.
         *     ### Next steps:
         *     * Once the `state` is `available`, the upload may be used to [create a mod file](#tag/mod_files/operation/createModFile).
         *     ### FAQ
         *     * How do I create an upload?
         *        * Use [create upload](#tag/uploads/operation/createUpload) to start a new upload session.
         */
        get: operations["getUpload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create upload
         * @description Creates a new upload session. This allows you to upload data for a new mod file.
         *     ### Next steps:
         *     * Call `PUT` with your file data to the returned `presigned_url`. Recommended for files up to 100Mb.
         *        * Files larger than 100Mb should use the multi part upload approach **(NOTE: Not yet available)**.
         *     * Once all data is uploaded, [finalise the upload](#tag/uploads/operation/finaliseUpload).
         */
        post: operations["createUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{id}/finalise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finalise upload
         * @description Closes the upload session once all data is uploaded. Sessions must be closed before you can use the upload as a mod file.
         *     ### Next steps:
         *     * Wait for the upload to be ready for use as a mod file. Use [get upload](#tag/uploads/operation/getUpload) to check that `state`
         *       is `available`.
         *     * [Create a mod file](#tag/mod_files/operation/createModFile) from this upload.
         */
        post: operations["finaliseUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mod_files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create mod file
         * @description Creates a new mod file using the data from a finalised [upload session](#tag/uploads/operation/createUpload).
         */
        post: operations["createModFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_domain}/mods/{mod_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get mod details
         * @description Retrieve specified mod, from a specified game.
         */
        get: operations["getMod"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateModFileRequest: {
            /**
             * Format: uuid
             * @description Upload ID
             */
            upload_id: string;
            /** @description Mod UID */
            mod_uid: number;
            /** @description Mod file name */
            name: string;
            /** @description Mod file version */
            version: string;
            /** @description Description of the mod file */
            description?: string | null;
            /** @enum {string} */
            file_category: "main" | "optional" | "miscellaneous";
        };
        CreateUploadRequest: {
            /** @description Size of file in bytes */
            size_bytes: number;
            /** @description User-defined filename */
            filename: string;
        };
        CreateUploadSuccess: {
            /** @description Presigned url */
            presigned_url: string;
        } & {
            /**
             * Format: uuid
             * @description Upload ID
             */
            uuid: string;
            /** @description User ID */
            user_id?: number;
            /** @description Upload state */
            state: string;
        };
        FinaliseUploadSuccess: {
            /**
             * Format: uuid
             * @description Upload ID
             */
            uuid: string;
            /** @description User ID */
            user_id?: number;
            /** @description Upload state */
            state: string;
        };
        GetUploadSuccess: {
            /**
             * Format: uuid
             * @description Upload ID
             */
            uuid: string;
            /** @description User ID */
            user_id?: number;
            /** @description Upload state */
            state: string;
        };
        CreateModFileSuccess: {
            /**
             * Format: uuid
             * @description Mod File UID
             */
            uid: string;
            /** @description Mod file name */
            name: string;
            /** @enum {string} */
            file_category: "main" | "optional" | "miscellaneous";
        };
        Upload: {
            /**
             * Format: uuid
             * @description Upload ID
             */
            uuid: string;
            /** @description User ID */
            user_id?: number;
            /** @description Upload state */
            state: string;
        };
        ModFile: {
            /**
             * Format: uuid
             * @description Mod File UID
             */
            uid: string;
            /** @description Mod file name */
            name: string;
            /** @enum {string} */
            file_category: "main" | "optional" | "miscellaneous";
        };
        /** @enum {string} */
        ModFileCategory: "main" | "optional" | "miscellaneous";
        BadRequest: {
            /** @description Error message */
            error: string;
            /** @description List of validation errors */
            details: string[];
        };
        Forbidden: {
            /** @description Error message */
            error: string;
        };
        NotFound: {
            /** @description Error message */
            error: string;
        };
        UnprocessableEntity: {
            /** @description Error message */
            error: string;
        };
        GetModDetails: {
            /** @description Unique identifier for the mod */
            uid: number;
            /** @description Mod ID */
            mod_id: number;
            /** @description Game ID */
            game_id: number;
            /** @description Mod name (only shown if mod is available) */
            name?: string | null;
            /** @description Short summary of the mod (only shown if mod is available) */
            summary?: string | null;
            /** @description Full description of the mod (only shown if mod is available) */
            description?: string | null;
            /** @description URL to the mod's picture (only shown if mod is available) */
            picture_url?: string | null;
            /** @description Total download count (only shown if mod is available) */
            mod_downloads?: number | null;
            /** @description Unique download count (only shown if mod is available) */
            mod_unique_downloads?: number | null;
            /** @description Whether ratings are allowed for this mod */
            allow_rating: boolean;
            /** @description Game domain name */
            domain_name: string;
            /** @description Category ID */
            category_id: number;
            /** @description Current mod version */
            version: string;
            /** @description Number of endorsements */
            endorsement_count: number;
            /** @description Unix timestamp of when the mod was created */
            created_timestamp: number;
            /**
             * Format: date-time
             * @description ISO 8601 datetime of when the mod was created
             */
            created_time: string;
            /** @description Unix timestamp of when the mod was last updated */
            updated_timestamp: number;
            /**
             * Format: date-time
             * @description ISO 8601 datetime of when the mod was last updated
             */
            updated_time: string;
            /** @description Mod author name */
            author: string;
            /** @description Name of the user who uploaded the mod */
            uploaded_by: string;
            /** @description URL to the uploader's profile */
            uploaded_users_profile_url: string;
            /** @description Whether the mod contains adult content */
            contains_adult_content: boolean;
            /** @description Mod status */
            status: string;
            /** @description Whether the mod is available (published) */
            available: boolean;
        };
        Mod: {
            /** @description Unique identifier for the mod */
            uid: number;
            /** @description Mod ID */
            mod_id: number;
            /** @description Game ID */
            game_id: number;
            /** @description Mod name (only shown if mod is available) */
            name?: string | null;
            /** @description Short summary of the mod (only shown if mod is available) */
            summary?: string | null;
            /** @description Full description of the mod (only shown if mod is available) */
            description?: string | null;
            /** @description URL to the mod's picture (only shown if mod is available) */
            picture_url?: string | null;
            /** @description Total download count (only shown if mod is available) */
            mod_downloads?: number | null;
            /** @description Unique download count (only shown if mod is available) */
            mod_unique_downloads?: number | null;
            /** @description Whether ratings are allowed for this mod */
            allow_rating: boolean;
            /** @description Game domain name */
            domain_name: string;
            /** @description Category ID */
            category_id: number;
            /** @description Current mod version */
            version: string;
            /** @description Number of endorsements */
            endorsement_count: number;
            /** @description Unix timestamp of when the mod was created */
            created_timestamp: number;
            /**
             * Format: date-time
             * @description ISO 8601 datetime of when the mod was created
             */
            created_time: string;
            /** @description Unix timestamp of when the mod was last updated */
            updated_timestamp: number;
            /**
             * Format: date-time
             * @description ISO 8601 datetime of when the mod was last updated
             */
            updated_time: string;
            /** @description Mod author name */
            author: string;
            /** @description Name of the user who uploaded the mod */
            uploaded_by: string;
            /** @description URL to the uploader's profile */
            uploaded_users_profile_url: string;
            /** @description Whether the mod contains adult content */
            contains_adult_content: boolean;
            /** @description Mod status */
            status: string;
            /** @description Whether the mod is available (published) */
            available: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Uploads UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description Upload ID
                         */
                        uuid: string;
                        /** @description User ID */
                        user_id?: number;
                        /** @description Upload state */
                        state: string;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                        /** @description List of validation errors */
                        details: string[];
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
        };
    };
    createUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Size of file in bytes */
                    size_bytes: number;
                    /** @description User-defined filename */
                    filename: string;
                };
            };
        };
        responses: {
            /** @description Upload UUID and presigned url */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Presigned url */
                        presigned_url: string;
                    } & {
                        /**
                         * Format: uuid
                         * @description Upload ID
                         */
                        uuid: string;
                        /** @description User ID */
                        user_id?: number;
                        /** @description Upload state */
                        state: string;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                        /** @description List of validation errors */
                        details: string[];
                    };
                };
            };
        };
    };
    finaliseUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Uploads UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description Upload ID
                         */
                        uuid: string;
                        /** @description User ID */
                        user_id?: number;
                        /** @description Upload state */
                        state: string;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                        /** @description List of validation errors */
                        details: string[];
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
        };
    };
    createModFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description Upload ID
                     */
                    upload_id: string;
                    /** @description Mod UID */
                    mod_uid: number;
                    /** @description Mod file name */
                    name: string;
                    /** @description Mod file version */
                    version: string;
                    /** @description Description of the mod file */
                    description?: string | null;
                    /** @enum {string} */
                    file_category: "main" | "optional" | "miscellaneous";
                };
            };
        };
        responses: {
            /** @description ModFile */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description Mod File UID
                         */
                        uid: string;
                        /** @description Mod file name */
                        name: string;
                        /** @enum {string} */
                        file_category: "main" | "optional" | "miscellaneous";
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                        /** @description List of validation errors */
                        details: string[];
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
        };
    };
    getMod: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Game domain name */
                game_domain: string;
                /** @description Mod ID */
                mod_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mod details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Unique identifier for the mod */
                        uid: number;
                        /** @description Mod ID */
                        mod_id: number;
                        /** @description Game ID */
                        game_id: number;
                        /** @description Mod name (only shown if mod is available) */
                        name?: string | null;
                        /** @description Short summary of the mod (only shown if mod is available) */
                        summary?: string | null;
                        /** @description Full description of the mod (only shown if mod is available) */
                        description?: string | null;
                        /** @description URL to the mod's picture (only shown if mod is available) */
                        picture_url?: string | null;
                        /** @description Total download count (only shown if mod is available) */
                        mod_downloads?: number | null;
                        /** @description Unique download count (only shown if mod is available) */
                        mod_unique_downloads?: number | null;
                        /** @description Whether ratings are allowed for this mod */
                        allow_rating: boolean;
                        /** @description Game domain name */
                        domain_name: string;
                        /** @description Category ID */
                        category_id: number;
                        /** @description Current mod version */
                        version: string;
                        /** @description Number of endorsements */
                        endorsement_count: number;
                        /** @description Unix timestamp of when the mod was created */
                        created_timestamp: number;
                        /**
                         * Format: date-time
                         * @description ISO 8601 datetime of when the mod was created
                         */
                        created_time: string;
                        /** @description Unix timestamp of when the mod was last updated */
                        updated_timestamp: number;
                        /**
                         * Format: date-time
                         * @description ISO 8601 datetime of when the mod was last updated
                         */
                        updated_time: string;
                        /** @description Mod author name */
                        author: string;
                        /** @description Name of the user who uploaded the mod */
                        uploaded_by: string;
                        /** @description URL to the uploader's profile */
                        uploaded_users_profile_url: string;
                        /** @description Whether the mod contains adult content */
                        contains_adult_content: boolean;
                        /** @description Mod status */
                        status: string;
                        /** @description Whether the mod is available (published) */
                        available: boolean;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                        /** @description List of validation errors */
                        details: string[];
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error message */
                        error: string;
                    };
                };
            };
        };
    };
}
